### ISSUE TITLE
Android 2.3 support

### ISSUE THREAD

**Issue by miskiw** [gokercebeci/canvasResize#4]
The HTML 5 File API is not supported until Android 3.0 + (http://caniuse.com/filereader) so this plugin doesn't seem to be compatible with Android 2.3 as stated.

I was trying to use this plugin in an Android 2.3 phonegap application but "FileReader" is not available.

Also tested the following:

if (window.FileReader) {
     console.log("FileReader Supported");
} else {
     //This fires in Android 2.3 webview
     console.log("FileReader NOT SUPPORTED");
}

**Comment by notecode** [comment]
My android is 5.1.1, can not work. The preview image is black
